### ISSUE TITLE
時間表改用html寫

### ISSUE THREAD

**Issue by sih4sing5hong5** [TAI-BUN-EXPO/TAI-BUN-EXPO.github.io#8]
這馬改做圖，手機仔困擾：
1. 傷細oh看
2. 用3G，圖掠siunn久

@shiami  Gún按算改好下底ê時間表就好，kā圖提掉

![2019-10-29 20-45-59 的螢幕擷圖](https://user-images.githubusercontent.com/5996555/67768277-27687280-fa8d-11e9-9c78-797c7ddfc761.png)

**Comment by ngoohebi** [comment]
Hó, kám-siā!
